#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Add any missing language/locale to the overview's "Proofread in" bars.

WHY THIS EXISTS. The bar and the PREVIEW_LANGS map are generated by
build_overview.py from a SIX-ENTRY LANG_NAMES, so two markets had no way to be
proofread:

  Svenska        the preview files were being written all along
                 (welcome-0X-sv-proposed.html) and simply nothing referenced
                 them.
  English (US)   no file existed at all. translate_welcome.py writes one preview
                 per LANGUAGE, and en-US is not a language - it is English prose
                 with per-locale overrides. It differs from en-GB in dollars,
                 /en-us/ links and "includes shipping" where the others claim
                 VAT, which is exactly what a proofreader needs to see.

Rather than re-run build_overview.py, which regenerates the whole document and
would drop everything the refresh_* scripts have since patched in, this edits
the two places in place and is idempotent: a language already present is left
alone.

  python3 scripts/refresh_overview_previews.py
"""
import io, json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOC = os.path.join(ROOT, "behavioural-email-overview.html")
PROPOSALS = os.path.join(ROOT, "proposals")

# tag -> the button label. Order is the order they appear in the bar.
ADD = [("sv", "Svenska"), ("en-US", "English (US)")]


def main():
    s = io.open(DOC, encoding="utf-8").read()
    before = len(s)

    # ---- 1. PREVIEW_LANGS: key -> {tag: path}
    m = re.search(r"PREVIEW_LANGS = (\{.*?\});", s, re.S)
    if not m:
        print("PREVIEW_LANGS not found"); return 1
    langs = json.loads(m.group(1))
    added = {}
    for key, by_tag in langs.items():
        en = by_tag.get("en") or ""
        slug = re.match(r"proposals/(.+)-proposed\.html$", en)
        if not slug:
            continue
        slug = slug.group(1)
        for tag, _label in ADD:
            if tag in by_tag:
                continue
            rel = "proposals/%s-%s-proposed.html" % (slug, tag)
            if os.path.exists(os.path.join(ROOT, rel)):
                by_tag[tag] = rel
                added.setdefault(key, []).append(tag)
    s = s[:m.start(1)] + json.dumps(langs, ensure_ascii=False) + s[m.end(1):]

    # ---- 2. the buttons, only for keys that actually gained a preview
    n_btn = 0
    for key, tags in added.items():
        bar = re.search(
            r'(<div class="lgbar" data-key="%s">.*?)(<span class="lgbar-n")'
            % re.escape(key), s, re.S)
        if not bar:
            print("  no lgbar for %s" % key); continue
        btns = "".join(
            '<button class="lgb" data-key="%s" data-lg="%s" '
            'onclick="switchLang(this)">%s</button>'
            % (key, t, dict(ADD)[t]) for t in tags)
        s = s[:bar.end(1)] + btns + s[bar.end(1):]
        n_btn += len(tags)

    io.open(DOC, "w", encoding="utf-8").write(s)
    print("previews wired: %d keys gained a language, %d buttons added"
          % (len(added), n_btn))
    for key, tags in sorted(added.items()):
        print("   %-16s + %s" % (key, ", ".join(tags)))
    print("doc %d KB -> %d KB" % (before / 1024, len(s) / 1024))
    return 0


if __name__ == "__main__":
    sys.exit(main())
